services:
  - type: web
    name: crm-backend
    env: node
    buildCommand: cd api && npm install
    startCommand: cd api && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false